version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 767397938697.dkr.ecr.us-west-2.amazonaws.com
      - echo "Installing dependencies..."
  
  pre_build:
    commands:
      - echo Installing kubectl
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl    

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t pacman1 -f Application/docker/Dockerfile .
      - echo "Tagging Docker image..."
      - docker tag pacman1:latest 767397938697.dkr.ecr.us-west-2.amazonaws.com/pacman1:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 767397938697.dkr.ecr.us-west-2.amazonaws.com/pacman1:latest
      - echo "Configuring kubectl..."
      - aws eks update-kubeconfig --name EKScluster --region us-west-2
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f "Kubernetes Manifest/"
      - echo "Checking deployment status..."
      - kubectl get pods
      - echo Build completed on `date`