#---------------------------
#EKS CI/CD Pipeline Project
#Created by Vladimir Ziulin
#---------------------------

output "VPC_ID" {
  value = aws_vpc.VPC_Pipeline.id
  description = "The ID of the VPC"
}

output "VPC_CIDR" {
  value = aws_vpc.VPC_Pipeline.cidr_block
  description = "My VPC CIDR Block"
}

output "EKS_ID" {
  value       = aws_eks_cluster.main
  description = "EKS Cluster Id"
}
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "Region" {
  description = "AWS region."
  value       = var.Region
}

output "Public_A_ID" {
  value       = aws_subnet.Public_Subnet_A.id
  description = "Public Subnet A ID of VPC"
}

output "Private_A_ID" {
  value       = aws_subnet.Private_Subnet_A.id
  description = "Public Subnet B ID of VPC"
}

output "alb_dns_name" {
  description = "The DNS name of the load balancer"
  value       = try(data.aws_lb.app.dns_name, "ALB not found or not yet created")
}