apiVersion: v1
   kind: Secret
   metadata:
     name: mongodb-secret
   type: Opaque
   data:
     mongodb-root-password: MTIzMzMzMTIz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGODB_URL: "mongodb://mongodb.default.svc.cluster.local:27017"